name: Starship Rocket Test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  Workflow_dispatch:

jobs:
  liftoff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Starship Liftoff
        run: echo "Starship lifting off..."
        shell: bash

  landing:
    runs-on: ubuntu-latest
    steps:
      - name: Starship landing
        run: echo "Starship landing to base"
        shell: bash
